export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const NEW_CATEGORY = 'NEW_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';